import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import { DM_Sans } from 'next/font/google'
import '@fortawesome/fontawesome-free/css/all.min.css';
import "bootstrap/dist/css/bootstrap.min.css"
import ImportBs from "./importBs";
import "./globals.css";

const dmsans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmsans.className}>
        <ImportBs />
        <NextTopLoader
          color="#0db02b"
          height={4}
        />
        {children}
      </body>
    </html>
  );
}
